export const BASE_URL = process.env.REACT_APP_BASE_URL;

export const MODAL = {
  DISPLAY_MODAL: 'DISPLAY_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL'
}

export const AUTHORS = {
  GET_AUTHORS:'GET_AUTHORS',
  GET_AUTHORS_SUCCESSFUL:'GET_AUTHORS_SUCCESSFUL',
  GET_AUTHORS_FAILED: 'GET_AUTHORS_FAILED',
}

export const SEARCH = 'SEARCH';
export const SORT = 'SORT';

export const PUBLICATIONS = {
  GET_PUBLICATIONS_SUCCESSFUL:'GET_PUBLICATIONS_SUCCESSFUL',
  GET_PUBLICATIONS_FAILED: 'GET_PUBLICATIONS_FAILED',
  GET_PUBLICATIONS: 'GET_PUBLICATIONS',
  GET_PUBLICATIONS_FROM_AUTHOR: 'GET_PUBLICATIONS_FROM_AUTHOR',
  SET_PUBLICATIONS_FROM_AUTOR: 'SET_PUBLICATIONS_FROM_AUTOR',
  SELECT_AUTHOR: 'SELECT_AUTHOR',
}
